services:
  gate-api:
    image: datagutten/feig-py:api-latest
    pull_policy: always
    volumes:
    - ./gate_data:/data

  gate-log:
    image: datagutten/rfid-gate-log:backend
    pull_policy: always
    env_file:
    - .env
    depends_on:
    - gate-api

  nginx:
    image: datagutten/rfid-gate-log:nginx
    build:
      context: nginx
      additional_contexts:
        ghcr.io/datagutten/rfid-gate-log: service:gate-log
    restart: unless-stopped
    depends_on:
    - gate-log
    - grafana

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    depends_on:
    - gate-log
    volumes:
    - grafana-data:/var/lib/grafana
    - ./grafana/provisioning:/var/lib/grafana/provisioning
    environment:
    - GF_USERS_ALLOW_SIGN_UP=false
    - GF_SECURITY_ADMIN_USER=admin
    - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    - GF_SERVER_ROOT_URL=/grafana
    - GF_SERVER_SERVE_FROM_SUB_PATH=true
    - GF_PATHS_PROVISIONING=/var/lib/grafana/provisioning
    - GF_PLUGINS_PREINSTALL=yesoreyeram-infinity-datasource
    - TZ=${TIME_ZONE}

volumes:
  grafana-data: