# Generated by Django 6.0.2 on 2026-02-21 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Library branch name', max_length=100)),
                ('lms_url', models.URLField(blank=True, help_text='Library branch LMS url', null=True)),
                ('lms_user', models.CharField(blank=True, help_text='Library branch LMS user name', max_length=100, null=True)),
                ('lms_password', models.CharField(blank=True, help_text='Library branch LMS password', max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'branches',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('tag', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('serial', models.IntegerField(primary_key=True, serialize=False, verbose_name='Serial number')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gates', to='gate_log.branch')),
            ],
        ),
        migrations.CreateModel(
            name='PeopleCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('people_in', models.IntegerField()),
                ('people_out', models.IntegerField()),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people_count', to='gate_log.gate')),
            ],
            options={
                'unique_together': {('gate', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PeopleCounterTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('people_in', models.IntegerField()),
                ('people_out', models.IntegerField()),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people_count_time', to='gate_log.gate')),
            ],
            options={
                'unique_together': {('gate', 'time')},
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('tag', models.CharField(max_length=100, verbose_name='Tag')),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='gate_log.gate')),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='gate_log.title')),
            ],
            options={
                'verbose_name_plural': 'log entries',
                'unique_together': {('gate', 'time', 'tag')},
            },
        ),
    ]
