# Generated by Django 6.0 on 2026-04-07 20:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peoplecountertime',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
