# Generated by Django 6.0 on 2026-07-08 18:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate_log', '0002_alter_peoplecountertime_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peoplecounter',
            options={'verbose_name': 'People count per day'},
        ),
        migrations.AlterModelOptions(
            name='peoplecountertime',
            options={'verbose_name': 'People count'},
        ),
        migrations.AlterField(
            model_name='logentry',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='gate_log.title'),
        ),
        migrations.CreateModel(
            name='BufferRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', models.BinaryField()),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_data', to='gate_log.gate')),
                ('tags', models.ManyToManyField(related_name='raw_data', to='gate_log.logentry')),
            ],
        ),
    ]
