# Generated by Django 6.0 on 2026-07-09 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate_log', '0003_alter_peoplecounter_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='gate_log.title'),
        ),
    ]
