# Generated by Django 6.1 on 2026-08-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate_log', '0004_alter_logentry_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='title_unknown',
            field=models.BooleanField(default=False),
        ),
    ]
